"""Effect-style utilities for functional programming.

Inspired by Effect-TS/ZIO:
- Result[T, E] monad for error handling
- Maybe[T] monad for optional values
- pipe/compose for function composition
- retry/timeout/race for control flow
"""

from __future__ import annotations

from .race import async_race, race
from .retry import (
    async_retry_with_backoff,
    async_with_retry,
    retry_with_backoff,
    with_retry,
)
from .result import (
    Err,
    Maybe,
    NoneVal,
    Ok,
    Result,
    Some,
    async_collect_maybes,
    async_collect_results,
    async_pipe,
    async_result_from_fn,
    async_traverse_maybe,
    async_traverse_result,
    collect_maybes,
    collect_results,
    compose,
    constantly,
    ensure,
    err,
    filter_map,
    find_map,
    flatten,
    flatten_result,
    flip,
    get_or_else,
    identity,
    lift_maybe,
    lift_result,
    map_error,
    maybe_from_value,
    maybe_to_result,
    none,
    ok,
    option_to_result,
    partition_maybes,
    partition_results,
    pipe,
    recover,
    result_from_fn,
    result_to_maybe,
    sequence_maybes,
    sequence_results,
    some,
    tap,
    traverse_maybe,
    traverse_result,
    unless,
    when,
    with_default,
)
from .timeout import async_with_timeout, timeout_with_default, with_timeout

__all__ = [
    "async_race",
    "async_retry_with_backoff",
    "async_with_retry",
    "async_result_from_fn",
    "async_with_timeout",
    "async_collect_results",
    "async_collect_maybes",
    "async_pipe",
    "async_traverse_result",
    "async_traverse_maybe",
    "collect_maybes",
    "collect_results",
    "compose",
    "constantly",
    "ensure",
    "Err",
    "err",
    "filter_map",
    "find_map",
    "flatten",
    "flatten_result",
    "flip",
    "get_or_else",
    "identity",
    "lift_maybe",
    "lift_result",
    "map_error",
    "maybe_from_value",
    "maybe_to_result",
    "Maybe",
    "none",
    "NoneVal",
    "Ok",
    "ok",
    "option_to_result",
    "partition_maybes",
    "partition_results",
    "pipe",
    "race",
    "recover",
    "retry_with_backoff",
    "result_from_fn",
    "result_to_maybe",
    "Result",
    "sequence_maybes",
    "sequence_results",
    "Some",
    "some",
    "tap",
    "timeout_with_default",
    "traverse_maybe",
    "traverse_result",
    "unless",
    "when",
    "with_default",
    "with_retry",
    "with_timeout",
]