"""Seed data subpackage — domain-specific knowledge materials."""

from __future__ import annotations

from typing import Any, Dict, List

from .agent_dev import AGENT_DEV_MATERIALS
from .code_engineering import CODE_ENGINEERING_MATERIALS
from .daily_life import DAILY_LIFE_MATERIALS
from .data_science import DATA_SCIENCE_MATERIALS
from .database import DATABASE_MATERIALS
from .dev_ops import DEV_OPS_MATERIALS
from .llm_usage import LLM_USAGE_MATERIALS
from .math_reasoning import MATH_REASONING_MATERIALS
from .network_info import NETWORK_INFO_MATERIALS
from .project_mgmt import PROJECT_MGMT_MATERIALS
from .security import SECURITY_MATERIALS
from .system_admin import SYSTEM_ADMIN_MATERIALS
from .troubleshooting import TROUBLESHOOTING_MATERIALS

from .data_science_extended import DATA_SCIENCE_EXTENDED_MATERIALS
from .math_reasoning_extended import MATH_REASONING_EXTENDED_MATERIALS
from .security_extended import SECURITY_EXTENDED_MATERIALS
from .system_admin_extended import SYSTEM_ADMIN_EXTENDED_MATERIALS
from .troubleshooting_extended import TROUBLESHOOTING_EXTENDED_MATERIALS

MASSIVE_MATERIALS: List[Dict[str, Any]] = [
    *AGENT_DEV_MATERIALS,
    *DATABASE_MATERIALS,
    *LLM_USAGE_MATERIALS,
    *DATA_SCIENCE_MATERIALS,
    *SECURITY_MATERIALS,
    *SYSTEM_ADMIN_MATERIALS,
    *MATH_REASONING_MATERIALS,
    *TROUBLESHOOTING_MATERIALS,
    *DEV_OPS_MATERIALS,
    *CODE_ENGINEERING_MATERIALS,
    *PROJECT_MGMT_MATERIALS,
    *DAILY_LIFE_MATERIALS,
    *NETWORK_INFO_MATERIALS,
]

EXTENDED_MATERIALS: List[Dict[str, Any]] = [
    *MATH_REASONING_EXTENDED_MATERIALS,
    *TROUBLESHOOTING_EXTENDED_MATERIALS,
    *SECURITY_EXTENDED_MATERIALS,
    *DATA_SCIENCE_EXTENDED_MATERIALS,
    *SYSTEM_ADMIN_EXTENDED_MATERIALS,
]

__all__ = [
    "MASSIVE_MATERIALS",
    "EXTENDED_MATERIALS",
    "AGENT_DEV_MATERIALS",
    "CODE_ENGINEERING_MATERIALS",
    "DAILY_LIFE_MATERIALS",
    "DATA_SCIENCE_MATERIALS",
    "DATABASE_MATERIALS",
    "DEV_OPS_MATERIALS",
    "LLM_USAGE_MATERIALS",
    "MATH_REASONING_MATERIALS",
    "NETWORK_INFO_MATERIALS",
    "PROJECT_MGMT_MATERIALS",
    "SECURITY_MATERIALS",
    "SYSTEM_ADMIN_MATERIALS",
    "TROUBLESHOOTING_MATERIALS",
    "DATA_SCIENCE_EXTENDED_MATERIALS",
    "MATH_REASONING_EXTENDED_MATERIALS",
    "SECURITY_EXTENDED_MATERIALS",
    "SYSTEM_ADMIN_EXTENDED_MATERIALS",
    "TROUBLESHOOTING_EXTENDED_MATERIALS",
]
