"""P0-A exception governance — hotspot ``except Exception`` budgets."""

from __future__ import annotations

import pathlib
import re

import pytest

# SSOT: docs/plans/active/project-optimization-directions-2026-06.md §P0-A
_HOTSPOT_BUDGETS: dict[str, int] = {
    "butler/core/tool_batch.py": 0,
    "butler/core/agent_loop_phases.py": 0,
    "butler/gateway/locked_phases.py": 0,
    "butler/core/agent_loop.py": 0,
    "butler/core/agent_loop_ops.py": 2,
    "butler/gateway/locked_phases_ops.py": 2,
    "butler/memory/facade.py": 0,
    "butler/cli/doctor.py": 0,
    "butler/core/context_compressor.py": 0,
    "butler/gateway/message_pipelines.py": 0,
    "butler/gateway/inbound_pipeline.py": 0,
    "butler/gateway/inbound_pipeline_ops.py": 1,
    "butler/session/post_session_ops.py": 0,
    "butler/session/post_session_guard.py": 0,
    "butler/ops/health_report_turn.py": 0,
    "butler/core/context_compress_pipeline.py": 0,
    "butler/gateway/handler_helpers.py": 0,
    "butler/runtime/delegate_job.py": 0,
    "butler/runtime/delegate_job_finalize.py": 0,
    "butler/gateway/outbound_bridge.py": 0,
    "butler/memory/diagnostics.py": 0,
    "butler/ops/health_report.py": 0,
    "butler/tools/registry.py": 0,
    "butler/session/memory_prefetch.py": 0,
    "butler/permissions/rules.py": 0,
    "butler/permissions/rules_fail_closed.py": 0,
    "butler/permissions/rules_fail_closed_ops.py": 6,
    "butler/ops/execution_surface_diagnostics.py": 0,
    "butler/gateway/commands/memory_handlers.py": 0,
    "butler/memory/semantic_project.py": 0,
    "butler/memory/butler_memory.py": 0,
    "butler/memory/semantic_index.py": 0,
    "butler/memory/semantic_index_ops.py": 3,
    "butler/ops/rag_diagnostics.py": 0,
    "butler/ops/rag_diagnostics_ops.py": 0,
    "butler/memory/vector_store.py": 0,
    "butler/memory/vector_store_ops.py": 4,
    "butler/core/session_transcript.py": 0,
    "butler/core/session_transcript_ops.py": 0,
    "butler/tools/registry_gates.py": 0,
    "butler/tools/registry_invoke_ops.py": 1,
    "butler/ops/registry_diagnostics.py": 0,
    "butler/ops/registry_diagnostics_ops.py": 0,
    "butler/mcp/registry_hook.py": 0,
    "butler/mcp/registry_hook_ops.py": 1,
    "butler/gateway/commands/registry_handlers.py": 0,
    "butler/gateway/commands/registry_handlers_ops.py": 1,
    "butler/tools/registry_tools.py": 0,
    "butler/tools/registry_tools_ops.py": 1,
    "butler/gateway/commands/info_commands.py": 0,
    "butler/gateway/commands/info_commands_ops.py": 0,
    "butler/core/transcript_export.py": 0,
    "butler/core/transcript_export_ops.py": 0,
    "butler/core/transcript_search.py": 0,
    "butler/core/transcript_search_ops.py": 0,
    "butler/ops/embedding_diagnostics.py": 0,
    "butler/ops/embedding_diagnostics_ops.py": 0,
    "butler/ops/observation_diagnostics.py": 0,
    "butler/ops/observation_diagnostics_ops.py": 0,
    "butler/gateway/commands/help_handlers.py": 0,
    "butler/gateway/commands/help_handlers_ops.py": 0,
    "butler/tools/memory_tools.py": 0,
    "butler/tools/memory_tools_ops.py": 0,
    "butler/gateway/gateway_transcript.py": 0,
    "butler/gateway/gateway_transcript_ops.py": 0,
    "butler/gateway/command_registry.py": 0,
    "butler/gateway/command_registry_ops.py": 1,
    "butler/session/post_session.py": 0,
    "butler/session/post_session_extract_ops.py": 3,
    "butler/gateway/message_handler.py": 0,
    "butler/gateway/message_handler_ops.py": 1,
    "butler/gateway/turn_post_pipeline.py": 0,
    "butler/gateway/turn_post_pipeline_ops.py": 1,
    "butler/ops/degradation_registry.py": 0,
    "butler/ops/degradation_registry_ops.py": 0,
    "butler/gateway/hooks.py": 0,
    "butler/gateway/hooks_ops.py": 3,
    "butler/hooks/runner.py": 0,
    "butler/hooks/runner_ops.py": 1,
    "butler/core/context_pipeline.py": 0,
    "butler/core/context_pipeline_ops.py": 1,
    "butler/memory/coding_recall.py": 0,
    "butler/memory/transcript_recall.py": 0,
    "butler/memory/unified_recall.py": 0,
    "butler/memory/observation_recall.py": 0,
    "butler/memory/retrieval_telemetry.py": 0,
    "butler/memory/recall_ops.py": 0,
    "butler/memory/retrieval_telemetry_ops.py": 0,
    "butler/core/pim_state.py": 0,
    "butler/core/pim_state_ops.py": 0,
    "butler/tool_guardrails.py": 0,
    "butler/tool_guardrails_ops.py": 0,
    "butler/memory/embedding.py": 0,
    "butler/memory/embedding_ops.py": 2,
    "butler/tools/delegate_report.py": 0,
    "butler/tools/delegate_report_ops.py": 0,
    "butler/extensions/opencode.py": 0,
    "butler/extensions/opencode_ops.py": 2,
    "butler/tools/builtin_register.py": 0,
    "butler/tools/builtin_register_ops.py": 0,
    "butler/memory/facade_ops.py": 1,
    "butler/skills/router.py": 0,
    "butler/skills/router_ops.py": 0,
    "butler/cli/skills_registry.py": 0,
    "butler/cli/skills_registry_ops.py": 1,
    "butler/cli/memory_cli.py": 0,
    "butler/cli/memory_cli_ops.py": 0,
    "butler/core/tool_dispatch.py": 0,
    "butler/core/tool_dispatch_ops.py": 0,
    "butler/skills/learn.py": 0,
    "butler/skills/learn_ops.py": 2,
    "butler/skills/write_approval.py": 0,
    "butler/skills/write_approval_ops.py": 1,
    "butler/ops/onboard.py": 0,
    "butler/ops/onboard_ops.py": 0,
    "butler/memory_settings.py": 0,
    "butler/memory_settings_ops.py": 0,
    "butler/core/tool_dispatch_doom.py": 0,
    "butler/core/tool_dispatch_doom_ops.py": 1,
    "butler/ops/owner_pmf_metrics.py": 0,
    "butler/ops/owner_pmf_metrics_ops.py": 0,
    "butler/ops/owner_feedback.py": 0,
    "butler/ops/owner_feedback_ops.py": 0,
    "butler/core/schema_recovery.py": 0,
    "butler/core/schema_recovery_ops.py": 0,
    "butler/skills/manager.py": 0,
    "butler/skills/manager_ops.py": 0,
    "butler/core/best_effort.py": 3,
    "butler/core/events_sink.py": 0,
    "butler/core/events_sink_ops.py": 0,
    "butler/core/dev_state_context_adapter.py": 0,
    "butler/core/dev_state_context_adapter_ops.py": 1,
    "butler/core/tool_batch_finalize.py": 0,
    "butler/core/tool_batch_finalize_ops.py": 1,
    "butler/core/llm_retry.py": 0,
    "butler/core/llm_retry_ops.py": 1,
    "butler/core/metrics_sink.py": 0,
    "butler/core/metrics_sink_ops.py": 0,
    "butler/tools/project_tools.py": 0,
    "butler/tools/project_tools_ops.py": 0,
    "butler/tools/delegate_impl.py": 0,
    "butler/tools/delegate_impl_ops.py": 1,
    "butler/ops/owner_quality_surface.py": 0,
    "butler/ops/owner_quality_surface_ops.py": 0,
    "butler/core/memory_context_adapter.py": 0,
    "butler/core/memory_context_adapter_ops.py": 1,
    "butler/core/message_context_adapter.py": 0,
    "butler/core/message_context_adapter_ops.py": 1,
    "butler/core/review_context_adapter.py": 0,
    "butler/core/review_context_adapter_ops.py": 1,
    "butler/core/hook_context_adapter.py": 0,
    "butler/core/hook_context_adapter_ops.py": 1,
    "butler/core/dev_context_adapter.py": 0,
    "butler/core/dev_context_adapter_ops.py": 2,
    "butler/core/compaction_context_adapter.py": 0,
    "butler/core/compaction_context_adapter_ops.py": 1,
    "butler/core/compaction_status.py": 0,
    "butler/core/compaction_status_ops.py": 0,
    "butler/core/compaction_checkpoint.py": 0,
    "butler/core/compaction_checkpoint_ops.py": 0,
    "butler/core/reasoning_trace.py": 0,
    "butler/core/reasoning_trace_ops.py": 0,
    "butler/core/reflection_closure.py": 0,
    "butler/core/reflection_closure_ops.py": 0,
    "butler/core/post_compact_cleanup.py": 0,
    "butler/core/post_compact_cleanup_ops.py": 0,
    "butler/core/parallel_tools.py": 0,
    "butler/core/parallel_tools_ops.py": 1,
    "butler/core/hygiene_preflight.py": 0,
    "butler/core/reactive_compact.py": 0,
    "butler/core/reactive_compact_ops.py": 3,
    "butler/core/tool_orchestrator.py": 0,
    "butler/core/tool_orchestrator_ops.py": 1,
    "butler/core/compaction_task.py": 0,
    "butler/core/compaction_task_ops.py": 0,
    "butler/ops/butler_inbox.py": 0,
    "butler/ops/butler_inbox_ops.py": 0,
    "butler/core/tool_batch_runner.py": 0,
    "butler/core/tool_batch_runner_ops.py": 0,
    "butler/core/context_transform_registry.py": 0,
    "butler/core/context_transform_registry_ops.py": 0,
    "butler/core/model_context.py": 0,
    "butler/core/model_context_ops.py": 0,
    "butler/core/reflexion_ephemeral.py": 0,
    "butler/core/reflexion_ephemeral_ops.py": 0,
    "butler/core/session_hydration.py": 0,
    "butler/core/session_hydration_ops.py": 0,
    "butler/core/skill_tool_bridge.py": 0,
    "butler/core/skill_tool_bridge_ops.py": 0,
    "butler/ops/compaction_audit.py": 0,
    "butler/ops/compaction_audit_ops.py": 0,
    "butler/gateway/owner_surface.py": 0,
    "butler/gateway/owner_surface_ops.py": 0,
    "butler/core/batch_sequence_guard.py": 0,
    "butler/core/batch_sequence_guard_ops.py": 0,
    "butler/core/instruction_walkup.py": 0,
    "butler/core/instruction_walkup_ops.py": 0,
    "butler/gateway/runner.py": 0,
    "butler/gateway/runner_ops.py": 1,
    "butler/tools/path_safety.py": 0,
    "butler/tools/path_safety_ops.py": 0,
    "butler/tools/terminal_impl.py": 0,
    "butler/tools/terminal_impl_ops.py": 3,
    "butler/dev_engine/b9_delegate_gate.py": 0,
    "butler/dev_engine/b9_delegate_gate_ops.py": 0,
    "butler/report/generator.py": 0,
    "butler/report/generator_ops.py": 2,
    "butler/ops/harness_diagnostics.py": 0,
    "butler/ops/harness_diagnostics_ops.py": 0,
    "butler/dev_engine/delegate_finalize.py": 0,
    "butler/dev_engine/delegate_finalize_ops.py": 0,
    "butler/dev_engine/dev_tools.py": 0,
    "butler/dev_engine/dev_tools_ops.py": 1,
    "butler/orchestrator/memory_bridge.py": 0,
    "butler/orchestrator/memory_bridge_ops.py": 1,
    "butler/workflows/runner.py": 0,
    "butler/workflows/runner_ops.py": 0,
    "butler/tools/file_io.py": 0,
    "butler/tools/file_io_ops.py": 1,
    "butler/gateway/message_queue.py": 0,
    "butler/gateway/message_queue_ops.py": 3,
    "butler/gateway/platforms/wechat_ilink/adapter_outbound.py": 0,
    "butler/gateway/platforms/wechat_ilink/adapter_outbound_ops.py": 3,
    "butler/mcp/async_runner.py": 0,
    "butler/mcp/async_runner_ops.py": 0,
    "butler/session/lifecycle.py": 0,
    "butler/session/lifecycle_ops.py": 2,
    "butler/session/new_session.py": 0,
    "butler/session/new_session_ops.py": 0,
    "butler/dev_engine/delegate_init.py": 0,
    "butler/dev_engine/delegate_init_ops.py": 1,
    "butler/ops/openclaw_diagnostics.py": 0,
    "butler/ops/openclaw_diagnostics_ops.py": 0,
    "butler/memory/memory_benchmark.py": 0,
    "butler/memory/memory_benchmark_ops.py": 2,
    "butler/tools/mcp_self_service.py": 0,
    "butler/tools/mcp_self_service_ops.py": 1,
    "butler/ops/stack_diagnostics.py": 0,
    "butler/ops/stack_diagnostics_ops.py": 0,
    "butler/task_orchestrator.py": 0,
    "butler/task_orchestrator_ops.py": 1,
    "butler/dev_engine/dev_loop.py": 0,
    "butler/dev_engine/dev_loop_ops.py": 0,
    "butler/dev_engine/review_closure.py": 0,
    "butler/dev_engine/review_closure_ops.py": 0,
    "butler/workflow_step_runner.py": 0,
    "butler/workflow_step_runner_ops.py": 1,
    "butler/model_resolve.py": 0,
    "butler/model_resolve_ops.py": 0,
    "butler/dev_engine/verify.py": 0,
    "butler/dev_engine/verify_ops.py": 1,
    "butler/gateway/platforms/wechat_ilink/adapter_media.py": 0,
    "butler/gateway/platforms/wechat_ilink/adapter_media_ops.py": 1,
    "butler/gateway/platforms/wechat_ilink/adapter_lifecycle.py": 0,
    "butler/gateway/platforms/wechat_ilink/adapter_lifecycle_ops.py": 3,
    "butler/mcp/manager.py": 0,
    "butler/mcp/manager_ops.py": 2,
    "butler/memory/observer_queue.py": 0,
    "butler/memory/observer_queue_ops.py": 1,
    "butler/project/manager.py": 0,
    "butler/project/manager_ops.py": 0,
    "butler/registry/mcp_catalog.py": 0,
    "butler/registry/mcp_catalog_ops.py": 0,
    "butler/ops/eval_bridge.py": 0,
    "butler/ops/eval_bridge_ops.py": 3,
    "butler/ops/dev_eval.py": 0,
    "butler/ops/dev_eval_ops.py": 1,
    "butler/runtime/delegate_progress.py": 0,
    "butler/runtime/delegate_progress_ops.py": 1,
    "butler/memory/reindex.py": 0,
    "butler/memory/reindex_ops.py": 0,
    "butler/ops/delegate_failure_capture.py": 0,
    "butler/ops/delegate_failure_capture_ops.py": 1,
    "butler/project/preflight.py": 0,
    "butler/project/preflight_ops.py": 3,
    "butler/registry/skill_service.py": 0,
    "butler/registry/skill_service_ops.py": 1,
    "butler/memory/experience_mining.py": 0,
    "butler/memory/experience_mining_ops.py": 0,
    "butler/transport/llm_client.py": 0,
    "butler/transport/llm_client_ops.py": 3,
    "butler/plan/mode.py": 0,
    "butler/plan/mode_ops.py": 0,
    "butler/gateway/commands/dev_handlers.py": 0,
    "butler/gateway/commands/dev_handlers_ops.py": 0,
    "butler/tools/tool_audit.py": 0,
    "butler/tools/tool_audit_ops.py": 0,
    "butler/plan/markdown_sync.py": 0,
    "butler/plan/markdown_sync_ops.py": 0,
    "butler/ops/boundary_observability.py": 0,
    "butler/ops/boundary_observability_ops.py": 5,
    "butler/ops/owner_trust_surface.py": 0,
    "butler/ops/owner_trust_surface_ops.py": 0,
    "butler/ops/experience_selection_telemetry.py": 0,
    "butler/ops/experience_selection_telemetry_ops.py": 0,
    "butler/gateway/commands/dialog_commands.py": 0,
    "butler/gateway/commands/dialog_commands_ops.py": 0,
    "butler/tools/network_search_policy.py": 0,
    "butler/tools/network_search_policy_ops.py": 0,
    "butler/memory/vector_gc.py": 0,
    "butler/memory/vector_gc_ops.py": 3,
    "butler/gateway/platforms/wechat_ilink/_utils_legacy.py": 0,
    "butler/gateway/platforms/wechat_ilink/_utils_legacy_ops.py": 5,
    "butler/tools/orthogonality_lint.py": 0,
    "butler/tools/orthogonality_lint_ops.py": 0,
    "butler/gateway/message_pipelines_fail_closed.py": 0,
    "butler/gateway/message_pipelines_fail_closed_ops.py": 2,
    "butler/memory/experience_consolidation.py": 0,
    "butler/memory/experience_consolidation_ops.py": 1,
    "butler/core/tool_selector.py": 0,
    "butler/core/tool_selector_ops.py": 0,
    "butler/gateway/platforms/wechat_ilink/qr_phases.py": 0,
    "butler/gateway/platforms/wechat_ilink/qr_phases_ops.py": 3,
    "butler/tools/terminal_approval.py": 0,
    "butler/tools/terminal_approval_ops.py": 0,
    "butler/tools/builtin_impl.py": 0,
    "butler/tools/builtin_impl_ops.py": 2,
    "butler/prompt_eval/corpus_bridge.py": 0,
    "butler/prompt_eval/corpus_bridge_ops.py": 3,
    "butler/hooks/telemetry.py": 0,
    "butler/hooks/telemetry_ops.py": 0,
    "butler/core/two_phase_confirm.py": 0,
    "butler/core/two_phase_confirm_ops.py": 1,
    "butler/gateway/delegate_push_dedup.py": 0,
    "butler/gateway/delegate_push_dedup_ops.py": 0,
    "butler/mcp/config.py": 0,
    "butler/mcp/config_ops.py": 1,
    "butler/tools/delegate_prepare.py": 0,
    "butler/tools/delegate_prepare_ops.py": 0,
    "butler/hooks/loader.py": 0,
    "butler/hooks/loader_ops.py": 2,
    "butler/core/session_todos.py": 0,
    "butler/core/session_todos_ops.py": 0,
    "butler/mcp/deferred.py": 0,
    "butler/mcp/deferred_ops.py": 1,
    "butler/gateway/inbound_media.py": 0,
    "butler/gateway/inbound_media_ops.py": 3,
    "butler/tools/delegate_subagent.py": 0,
    "butler/tools/delegate_subagent_ops.py": 0,
    "butler/experiments/ledger.py": 0,
    "butler/experiments/ledger_ops.py": 0,
    "butler/ops/security_audit.py": 0,
    "butler/ops/security_audit_ops.py": 1,
    "butler/runtime/service.py": 0,
    "butler/runtime/service_ops.py": 0,
    "butler/tools/butlerignore.py": 0,
    "butler/tools/butlerignore_ops.py": 0,
    "butler/ops/terminal_sandbox_diagnostics.py": 0,
    "butler/ops/terminal_sandbox_diagnostics_ops.py": 0,
    "butler/memory/owner_experience_seed.py": 0,
    "butler/memory/owner_experience_seed_ops.py": 0,
    "butler/core/mode_classifier.py": 0,
    "butler/core/mode_classifier_ops.py": 1,
    "butler/registry/mcp_install.py": 0,
    "butler/registry/mcp_install_ops.py": 3,
    "butler/gateway/session_registry.py": 0,
    "butler/gateway/session_registry_ops.py": 1,
    "butler/memory/metrics_persist.py": 0,
    "butler/memory/metrics_persist_ops.py": 0,
    "butler/dev_engine/coding_knowledge.py": 0,
    "butler/dev_engine/coding_knowledge_ops.py": 0,
    "butler/ops/eval_experiment.py": 0,
    "butler/ops/eval_experiment_ops.py": 1,
    "butler/tools/data_query.py": 0,
    "butler/tools/data_query_ops.py": 1,
    "butler/memory/search_result.py": 0,
    "butler/memory/search_result_ops.py": 0,
    "butler/registry/mcp_merge.py": 0,
    "butler/registry/mcp_merge_ops.py": 1,
    "butler/memory/scope_diagnostics.py": 0,
    "butler/memory/scope_diagnostics_ops.py": 0,
    "butler/dev_engine/loop_plugin.py": 0,
    "butler/dev_engine/loop_plugin_ops.py": 0,
    "butler/ops/eval_regression.py": 0,
    "butler/ops/eval_regression_ops.py": 1,
    "butler/ops/eval_feedback.py": 0,
    "butler/ops/eval_feedback_ops.py": 1,
    "butler/ops/wechat_corpus_eval.py": 0,
    "butler/ops/wechat_corpus_eval_ops.py": 0,
    "butler/ops/memory_eval.py": 0,
    "butler/ops/memory_eval_ops.py": 1,
    "butler/mcp/client_stdio.py": 0,
    "butler/mcp/client_stdio_ops.py": 1,
    "butler/tools/tool_implicit_context.py": 0,
    "butler/tools/tool_implicit_context_ops.py": 0,
    "butler/dev_engine/dev_context.py": 0,
    "butler/dev_engine/dev_context_ops.py": 0,
    "butler/transport/fusion_client.py": 0,
    "butler/transport/fusion_client_ops.py": 1,
    "butler/tools/knowledge_search.py": 0,
    "butler/tools/knowledge_search_ops.py": 0,
    "butler/core/hygiene_preflight_ops.py": 1,
    "butler/session/post_session_guard_ops.py": 1,
    "butler/runtime/delegate_job_finalize_ops.py": 1,
    "butler/orchestrator/prompt_assembler.py": 0,
    "butler/orchestrator/prompt_assembler_ops.py": 0,
}

_EXCEPT_RE = re.compile(r"^\s*except\s+Exception\b", re.MULTILINE)


def _count_except_exception(rel_path: str) -> int:
    text = pathlib.Path(rel_path).read_text(encoding="utf-8")
    return len(_EXCEPT_RE.findall(text))


@pytest.mark.module_test
@pytest.mark.parametrize("rel_path,max_allowed", list(_HOTSPOT_BUDGETS.items()))
def test_p0a_hotspot_except_exception_budget(rel_path: str, max_allowed: int):
    count = _count_except_exception(rel_path)
    assert count <= max_allowed, (
        f"{rel_path} has {count} bare `except Exception` (budget {max_allowed}); "
        "use safe_best_effort / _record_skipped_plugin or narrow the exception type"
    )


def test_record_skipped_plugin_emits_best_effort_metric(monkeypatch):
    from butler.core.agent_loop import AgentLoop

    recorded: list[tuple[str, BaseException]] = []

    def _capture(label: str, exc: BaseException) -> None:
        recorded.append((label, exc))

    monkeypatch.setattr(
        "butler.core.best_effort.record_best_effort_skip",
        _capture,
    )
    metrics: list[tuple[str, dict]] = []

    def _inc(name: str, *, labels: dict | None = None) -> None:
        metrics.append((name, labels or {}))

    monkeypatch.setattr("butler.ops.runtime_metrics.inc", _inc)

    loop = AgentLoop.__new__(AgentLoop)
    loop.diagnostics = {}
    loop._record_skipped_plugin("test_plugin", RuntimeError("boom"))

    assert recorded[0][0] == "agent_loop.test_plugin"
    assert isinstance(recorded[0][1], RuntimeError)
    assert str(recorded[0][1]) == "boom"
    assert metrics == [("best_effort_skip", {"path": "agent_loop.test_plugin"})]
    assert loop.diagnostics["skipped"][0]["plugin"] == "test_plugin"
