"""P1-C module split — line budgets for core hot paths."""

from __future__ import annotations

import pathlib

import pytest

# SSOT: docs/plans/active/project-optimization-directions-2026-06.md §P1-C
_FILE_BUDGETS: dict[str, int] = {
    "butler/core/llm_retry.py": 90,
    "butler/core/context_compress_pipeline.py": 200,
    "butler/core/context_compress_support.py": 220,
    "butler/core/context_compress_hooks.py": 140,
    "butler/core/agent_loop_ops.py": 200,
    "butler/gateway/locked_phases_ops.py": 80,
    "butler/gateway/message_pipelines_fail_closed.py": 160,
    "butler/gateway/inbound_pipeline_ops.py": 40,
    "butler/session/post_session_guard.py": 40,
    "butler/ops/rag_diagnostics_ops.py": 130,
    "butler/memory/vector_store_ops.py": 80,
    "butler/core/session_transcript_ops.py": 100,
    "butler/tools/registry_invoke_ops.py": 55,
    "butler/ops/registry_diagnostics_ops.py": 120,
    "butler/mcp/registry_hook_ops.py": 140,
    "butler/gateway/commands/registry_handlers_ops.py": 80,
    "butler/tools/registry_tools_ops.py": 45,
    "butler/gateway/commands/info_commands_ops.py": 60,
    "butler/core/transcript_export_ops.py": 70,
    "butler/core/transcript_search_ops.py": 40,
    "butler/ops/embedding_diagnostics_ops.py": 35,
    "butler/ops/observation_diagnostics_ops.py": 45,
    "butler/gateway/commands/help_handlers_ops.py": 30,
    "butler/tools/memory_tools_ops.py": 25,
    "butler/gateway/gateway_transcript_ops.py": 35,
    "butler/gateway/command_registry_ops.py": 35,
    "butler/session/post_session_extract_ops.py": 160,
    "butler/gateway/message_handler_ops.py": 60,
    "butler/gateway/turn_post_pipeline_ops.py": 35,
    "butler/ops/degradation_registry_ops.py": 280,
    "butler/gateway/hooks_ops.py": 45,
    "butler/hooks/runner_ops.py": 130,
    "butler/core/context_pipeline_ops.py": 230,
    "butler/memory/recall_ops.py": 60,
    "butler/memory/retrieval_telemetry_ops.py": 40,
    "butler/core/tool_batch_finalize.py": 150,
    "butler/core/tool_dispatch.py": 235,
    "butler/core/tool_batch.py": 430,
    "butler/runtime/delegate_job.py": 340,
    "butler/runtime/delegate_job_finalize.py": 180,
    "butler/memory/diagnostics_collect.py": 180,
    "butler/ops/health_report_turn.py": 280,
    "butler/tools/registry_gates.py": 340,
    "butler/session/memory_prefetch_ops.py": 500,
    "butler/permissions/rules_context.py": 170,
    "butler/ops/execution_surface_collect.py": 360,
    "butler/gateway/commands/memory_handlers_ops.py": 200,
    "butler/memory/semantic_project_ops.py": 150,
    "butler/memory/butler_memory_ops.py": 100,
    "butler/memory/semantic_index_ops.py": 270,
    "butler/core/pim_state_ops.py": 95,
    "butler/tool_guardrails_ops.py": 80,
    "butler/memory/embedding_ops.py": 85,
    "butler/tools/delegate_report_ops.py": 110,
    "butler/extensions/opencode_ops.py": 120,
    "butler/tools/builtin_register_ops.py": 100,
    "butler/skills/router_ops.py": 60,
    "butler/cli/skills_registry_ops.py": 55,
    "butler/cli/memory_cli_ops.py": 30,
    "butler/core/tool_dispatch_ops.py": 35,
    "butler/skills/learn_ops.py": 40,
    "butler/skills/write_approval_ops.py": 40,
    "butler/ops/onboard_ops.py": 30,
    "butler/memory_settings_ops.py": 30,
    "butler/core/tool_dispatch_doom_ops.py": 50,
    "butler/ops/owner_pmf_metrics_ops.py": 25,
    "butler/ops/owner_feedback_ops.py": 25,
    "butler/core/schema_recovery_ops.py": 25,
    "butler/skills/manager_ops.py": 90,
    "butler/gateway/outbound_bridge_ops.py": 120,
    "butler/permissions/rules_fail_closed.py": 25,
    "butler/permissions/rules_fail_closed_ops.py": 130,
    "butler/core/events_sink_ops.py": 55,
    "butler/core/dev_state_context_adapter_ops.py": 120,
    "butler/core/llm_retry_ops.py": 90,
    "butler/core/tool_batch_finalize_ops.py": 40,
    "butler/core/llm_retry_ops.py": 200,
    "butler/core/metrics_sink_ops.py": 55,
    "butler/tools/project_tools_ops.py": 90,
    "butler/tools/delegate_impl_ops.py": 225,
    "butler/ops/owner_quality_surface_ops.py": 160,
    "butler/core/memory_context_adapter_ops.py": 120,
    "butler/core/message_context_adapter_ops.py": 90,
    "butler/core/review_context_adapter_ops.py": 180,
    "butler/core/hook_context_adapter_ops.py": 55,
    "butler/core/dev_context_adapter_ops.py": 120,
    "butler/core/compaction_context_adapter_ops.py": 110,
    "butler/core/compaction_status_ops.py": 55,
    "butler/core/compaction_checkpoint_ops.py": 55,
    "butler/core/reasoning_trace_ops.py": 130,
    "butler/core/reflection_closure_ops.py": 45,
    "butler/core/post_compact_cleanup_ops.py": 230,
    "butler/core/parallel_tools_ops.py": 80,
    "butler/core/hygiene_preflight_ops.py": 85,
    "butler/core/reactive_compact_ops.py": 110,
    "butler/core/tool_orchestrator_ops.py": 200,
    "butler/core/compaction_task_ops.py": 220,
    "butler/ops/butler_inbox_ops.py": 160,
    "butler/core/tool_batch_runner_ops.py": 30,
    "butler/core/context_transform_registry_ops.py": 30,
    "butler/core/model_context_ops.py": 45,
    "butler/core/reflexion_ephemeral_ops.py": 40,
    "butler/core/session_hydration_ops.py": 90,
    "butler/core/skill_tool_bridge_ops.py": 90,
    "butler/ops/compaction_audit_ops.py": 40,
    "butler/gateway/owner_surface_ops.py": 130,
    "butler/core/batch_sequence_guard_ops.py": 55,
    "butler/core/instruction_walkup_ops.py": 40,
    "butler/gateway/runner_ops.py": 200,
    "butler/tools/path_safety_ops.py": 200,
    "butler/tools/terminal_impl_ops.py": 100,
    "butler/dev_engine/b9_delegate_gate_ops.py": 120,
    "butler/report/generator_ops.py": 180,
    "butler/ops/harness_diagnostics_ops.py": 160,
    "butler/dev_engine/delegate_finalize_ops.py": 200,
    "butler/dev_engine/dev_tools_ops.py": 150,
    "butler/orchestrator/memory_bridge_ops.py": 120,
    "butler/workflows/runner_ops.py": 230,
    "butler/tools/file_io_ops.py": 70,
    "butler/gateway/message_queue_ops.py": 150,
    "butler/gateway/platforms/wechat_ilink/adapter_outbound_ops.py": 210,
    "butler/mcp/async_runner_ops.py": 100,
    "butler/session/lifecycle_ops.py": 120,
    "butler/session/new_session_ops.py": 100,
    "butler/dev_engine/delegate_init_ops.py": 200,
    "butler/ops/openclaw_diagnostics_ops.py": 130,
    "butler/memory/memory_benchmark_ops.py": 60,
    "butler/tools/mcp_self_service_ops.py": 60,
    "butler/ops/stack_diagnostics_ops.py": 140,
    "butler/task_orchestrator_ops.py": 80,
    "butler/dev_engine/dev_loop_ops.py": 70,
    "butler/dev_engine/review_closure_ops.py": 80,
    "butler/workflow_step_runner_ops.py": 80,
    "butler/model_resolve_ops.py": 120,
    "butler/dev_engine/verify_ops.py": 130,
    "butler/gateway/platforms/wechat_ilink/adapter_media_ops.py": 50,
    "butler/gateway/platforms/wechat_ilink/adapter_lifecycle_ops.py": 60,
    "butler/mcp/manager_ops.py": 90,
    "butler/memory/observer_queue_ops.py": 70,
    "butler/project/manager_ops.py": 80,
    "butler/registry/mcp_catalog_ops.py": 80,
    "butler/ops/eval_bridge_ops.py": 70,
    "butler/ops/dev_eval_ops.py": 40,
    "butler/runtime/delegate_progress_ops.py": 90,
    "butler/memory/reindex_ops.py": 130,
    "butler/ops/delegate_failure_capture_ops.py": 180,
    "butler/project/preflight_ops.py": 100,
    "butler/registry/skill_service_ops.py": 120,
    "butler/memory/experience_mining_ops.py": 90,
    "butler/transport/llm_client_ops.py": 80,
    "butler/plan/mode_ops.py": 100,
    "butler/gateway/commands/dev_handlers_ops.py": 120,
    "butler/tools/tool_audit_ops.py": 130,
    "butler/plan/markdown_sync_ops.py": 60,
    "butler/ops/boundary_observability_ops.py": 140,
    "butler/ops/owner_trust_surface_ops.py": 100,
    "butler/ops/experience_selection_telemetry_ops.py": 80,
    "butler/gateway/commands/dialog_commands_ops.py": 100,
    "butler/tools/network_search_policy_ops.py": 100,
    "butler/memory/vector_gc_ops.py": 45,
    "butler/gateway/platforms/wechat_ilink/_utils_legacy_ops.py": 90,
    "butler/tools/orthogonality_lint_ops.py": 110,
    "butler/gateway/message_pipelines_fail_closed_ops.py": 60,
    "butler/memory/experience_consolidation_ops.py": 45,
    "butler/core/tool_selector_ops.py": 70,
    "butler/gateway/platforms/wechat_ilink/qr_phases_ops.py": 55,
    "butler/tools/terminal_approval_ops.py": 60,
    "butler/tools/builtin_impl_ops.py": 55,
    "butler/prompt_eval/corpus_bridge_ops.py": 45,
    "butler/hooks/telemetry_ops.py": 75,
    "butler/core/two_phase_confirm_ops.py": 80,
    "butler/gateway/delegate_push_dedup_ops.py": 90,
    "butler/mcp/config_ops.py": 60,
    "butler/tools/delegate_prepare_ops.py": 50,
    "butler/hooks/loader_ops.py": 50,
    "butler/core/session_todos_ops.py": 40,
    "butler/mcp/deferred_ops.py": 70,
    "butler/gateway/inbound_media_ops.py": 65,
    "butler/tools/delegate_subagent_ops.py": 55,
    "butler/experiments/ledger_ops.py": 115,
    "butler/ops/security_audit_ops.py": 85,
    "butler/runtime/service_ops.py": 60,
    "butler/tools/butlerignore_ops.py": 30,
    "butler/ops/terminal_sandbox_diagnostics_ops.py": 65,
    "butler/memory/owner_experience_seed_ops.py": 35,
    "butler/core/mode_classifier_ops.py": 85,
    "butler/registry/mcp_install_ops.py": 80,
    "butler/gateway/session_registry_ops.py": 50,
    "butler/memory/metrics_persist_ops.py": 70,
    "butler/dev_engine/coding_knowledge_ops.py": 90,
    "butler/ops/eval_experiment_ops.py": 75,
    "butler/tools/data_query_ops.py": 110,
    "butler/memory/search_result_ops.py": 30,
    "butler/registry/mcp_merge_ops.py": 95,
    "butler/memory/scope_diagnostics_ops.py": 90,
    "butler/dev_engine/loop_plugin_ops.py": 145,
    "butler/ops/eval_regression_ops.py": 75,
    "butler/ops/eval_feedback_ops.py": 110,
    "butler/ops/wechat_corpus_eval_ops.py": 65,
    "butler/ops/memory_eval_ops.py": 55,
    "butler/mcp/client_stdio_ops.py": 45,
    "butler/tools/tool_implicit_context_ops.py": 60,
}

_PROCESS_TOOL_CALLS_BUDGET = 150
_COMPRESS_MESSAGES_DELEGATE_BUDGET = 25


@pytest.mark.module_test
@pytest.mark.parametrize("rel_path,max_lines", list(_FILE_BUDGETS.items()))
def test_p1c_module_line_budget(rel_path: str, max_lines: int):
    path = pathlib.Path(rel_path)
    count = sum(1 for _ in path.read_text(encoding="utf-8").splitlines())
    assert count <= max_lines, f"{rel_path} has {count} lines (budget {max_lines})"


@pytest.mark.module_test
def test_process_tool_calls_orchestrator_budget():
    text = pathlib.Path("butler/core/tool_batch.py").read_text(encoding="utf-8")
    start = text.index("def process_tool_calls(")
    end = text.index("\n\nfrom butler.core.tool_batch_finalize", start)
    block = text[start:end]
    lines = block.count("\n") + 1
    assert lines <= _PROCESS_TOOL_CALLS_BUDGET, (
        f"process_tool_calls block is {lines} lines (budget {_PROCESS_TOOL_CALLS_BUDGET})"
    )


@pytest.mark.module_test
def test_compress_messages_delegates_to_pipeline():
    text = pathlib.Path("butler/core/context_compressor.py").read_text(encoding="utf-8")
    start = text.index("def compress_messages(")
    end = text.index("\n", text.index("run_compress_messages", start))
    block = text[start:end]
    lines = block.count("\n") + 1
    assert lines <= _COMPRESS_MESSAGES_DELEGATE_BUDGET
    assert "run_compress_messages" in block
