from __future__ import annotations

from butler.dev_engine.coding_knowledge.elements import (
    BASELINE_THEOREMS,
    CodingElement,
    ELEMENT_THEOREM_MAP,
    ELEMENT_VERIFICATION_PROPERTIES,
    decompose_task,
)
from butler.dev_engine.coding_knowledge.theorems import (
    CodingTheorem,
    TheoremCheckResult,
    TheoremChecker,
    TheoremLibrary,
    THEOREM_CHECKERS,
    build_default_theorem_library,
    _check_t01_determinism,
    _check_t02_composability,
    _check_t03_type_safety,
    _check_t04_termination,
    _check_t05_state_isolation,
    _check_t06_exception_safety,
    _check_t07_idempotency,
    _check_t08_resource_lifecycle,
    _check_t09_contract_adherence,
    _check_t10_trust_boundary,
)
from butler.dev_engine.coding_knowledge.ast_analysis import (
    _try_parse_ast,
    _ast_has_nondeterministic_call,
    _ast_while_true_missing_break,
    _ast_has_global_stmt,
    _ast_has_bare_except_pass,
    _ast_try_without_handler,
    _ast_has_eval_call,
    _ast_open_without_context_manager,
    _ast_http_request_without_status_check,
    _ast_external_input_without_validation,
)
from butler.dev_engine.coding_knowledge.verification import (
    DualVerificationResult,
    dual_verify,
    verify_theorems,
)
from butler.dev_engine.coding_knowledge.context import (
    CodingKnowledgeContext,
    process_task,
)
from butler.dev_engine.coding_knowledge.generation import (
    SynthConstraint,
    SynthResult,
    TestCase,
    GenTCResult,
    THEOREM_TEST_PATTERNS,
    extract_experience_candidate,
    format_coding_guidance_block,
    generate_test_cases,
    synthesize,
)
from butler.dev_engine.coding_knowledge.experience import (
    CodingExperience,
    ExperienceLibrary,
)

__all__ = [
    "BASELINE_THEOREMS",
    "CodingElement",
    "ELEMENT_THEOREM_MAP",
    "ELEMENT_VERIFICATION_PROPERTIES",
    "decompose_task",
    "CodingTheorem",
    "TheoremCheckResult",
    "TheoremChecker",
    "TheoremLibrary",
    "THEOREM_CHECKERS",
    "build_default_theorem_library",
    "_try_parse_ast",
    "_ast_has_nondeterministic_call",
    "_ast_while_true_missing_break",
    "_ast_has_global_stmt",
    "_ast_has_bare_except_pass",
    "_ast_try_without_handler",
    "_ast_has_eval_call",
    "_ast_open_without_context_manager",
    "_ast_http_request_without_status_check",
    "_ast_external_input_without_validation",
    "_check_t01_determinism",
    "_check_t02_composability",
    "_check_t03_type_safety",
    "_check_t04_termination",
    "_check_t05_state_isolation",
    "_check_t06_exception_safety",
    "_check_t07_idempotency",
    "_check_t08_resource_lifecycle",
    "_check_t09_contract_adherence",
    "_check_t10_trust_boundary",
    "DualVerificationResult",
    "dual_verify",
    "verify_theorems",
    "CodingKnowledgeContext",
    "process_task",
    "SynthConstraint",
    "SynthResult",
    "TestCase",
    "GenTCResult",
    "THEOREM_TEST_PATTERNS",
    "extract_experience_candidate",
    "format_coding_guidance_block",
    "generate_test_cases",
    "synthesize",
    "CodingExperience",
    "ExperienceLibrary",
]
