"""CDN download/upload, inbound parsing, local media cache (PROD-P2-01)."""

from butler.gateway.platforms.wechat_ilink._utils_legacy import (
    _assert_wechat_cdn_url,
    _cdn_download_url,
    _cdn_upload_url,
    _coerce_bool,
    _content_dedup_ttl,
    _download_and_decrypt_media,
    _download_bytes,
    _extract_text,
    _guess_chat_type,
    _is_stale_session_ret,
    _make_ssl_connector,
    _media_reference,
    _message_id_dedup_ttl,
    _message_type_from_media,
    _mime_from_filename,
    _random_wechat_uin,
    _safe_id,
    cache_audio_from_bytes,
    cache_document_from_bytes,
    cache_image_from_bytes,
)

__all__ = [
    "_assert_wechat_cdn_url",
    "_cdn_download_url",
    "_cdn_upload_url",
    "_coerce_bool",
    "_content_dedup_ttl",
    "_download_and_decrypt_media",
    "_download_bytes",
    "_extract_text",
    "_guess_chat_type",
    "_is_stale_session_ret",
    "_make_ssl_connector",
    "_media_reference",
    "_message_id_dedup_ttl",
    "_message_type_from_media",
    "_mime_from_filename",
    "_random_wechat_uin",
    "_safe_id",
    "cache_audio_from_bytes",
    "cache_document_from_bytes",
    "cache_image_from_bytes",
]
